export enum Permissions {
  USER_LIST = "user:list",
  USER_READ = "user:read",
  USER_CREATE = "user:create",
  USER_EDIT = "user:edit",
  USER_DELETE = "user:delete",
  NEWS_LIST = "news:list",
  NEWS_READ = "news:read",
  NEWS_CREATE = "news:create",
  NEWS_EDIT = "news:edit",
  NEWS_DELETE = "news:delete",
  PEOPLE_LIST = "people:list",
  CONFIGURATION_VIEW = "configuration:view",
  ROLE_LIST = "role:list",
  ROLE_CREATE = "role:create",
  ROLE_EDIT = "role:edit",
  ROLE_DELETE = "role:delete",
}
